"""
convert_image.py

Convert any image to input_image.h for the ESP32 inference engine.

Usage: python scripts/convert_image.py <image_path> [output_path]

Steps:
  1. Load image (PNG/JPG/etc)
  2. Resize to 32x32 (CIFAR-10 input size)
  3. Normalize with CIFAR-10 mean/std
  4. Quantize to uint8 using model input scale & zero_point
  5. Write input_image.h
"""
import sys
import os
import numpy as np
from PIL import Image

# ---- Model input quantization parameters (from model_int8.onnx) ----
INPUT_SCALE = 0.016141029074788094
INPUT_ZP    = 123

# ---- CIFAR-10 normalization (same as train.py) ----
CIFAR10_MEAN = np.array([0.4914, 0.4822, 0.4465], dtype=np.float32)
CIFAR10_STD  = np.array([0.2470, 0.2435, 0.2616], dtype=np.float32)

CIFAR10_CLASSES = [
    "airplane", "automobile", "bird", "cat", "deer",
    "dog", "frog", "horse", "ship", "truck",
]


def convert_image(image_path, output_path):
    """Load image, preprocess, quantize, and write C header."""
    # 1. Load image
    img = Image.open(image_path).convert("RGB")
    orig_size = img.size
    print(f"  Loaded: {image_path}")
    print(f"  Original size: {orig_size[0]}x{orig_size[1]}")

    # 2. Resize to 32x32 (bilinear interpolation)
    img = img.resize((32, 32), Image.BILINEAR)
    print(f"  Resized to: 32x32")

    # 3. Convert to float [0, 1] and normalize
    arr = np.array(img, dtype=np.float32) / 255.0  # (32, 32, 3) HWC
    # Normalize per channel
    for c in range(3):
        arr[:, :, c] = (arr[:, :, c] - CIFAR10_MEAN[c]) / CIFAR10_STD[c]

    # 4. Convert to CHW (NCHW format, no batch dim)
    arr_chw = arr.transpose(2, 0, 1)  # (3, 32, 32)
    print(f"  Normalized range: [{arr_chw.min():.4f}, {arr_chw.max():.4f}]")

    # 5. Quantize to uint8
    arr_q = np.clip(np.round(arr_chw / INPUT_SCALE + INPUT_ZP), 0, 255).astype(np.uint8)
    print(f"  Quantized range: [{arr_q.min()}, {arr_q.max()}]")
    print(f"  Total size: {arr_q.size} bytes")

    # 6. Write C header
    flat = arr_q.flatten()
    basename = os.path.splitext(os.path.basename(image_path))[0]

    lines = []
    lines.append("/* Generated by convert_image.py */")
    lines.append(f"/* Source: {os.path.basename(image_path)} ({orig_size[0]}x{orig_size[1]} -> 32x32) */")
    lines.append("#ifndef INPUT_IMAGE_H")
    lines.append("#define INPUT_IMAGE_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append('#include "model.h"')
    lines.append("")
    lines.append(f"/* Quantized with scale={INPUT_SCALE:.10e}, zp={INPUT_ZP} */")
    lines.append(f"/* CIFAR-10 classes: airplane(0), automobile(1), bird(2), cat(3), deer(4), */")
    lines.append(f"/*   dog(5), frog(6), horse(7), ship(8), truck(9) */")
    lines.append(f'#define EXPECTED_CLASS -1   /* set manually if known */')
    lines.append(f'#define EXPECTED_CLASS_NAME "unknown"')
    lines.append("")
    lines.append(f"static const uint8_t input_image[INPUT_SIZE] = {{")
    per_line = 16
    for i in range(0, len(flat), per_line):
        chunk = flat[i:i+per_line]
        lines.append("    " + ", ".join(f"{v}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* INPUT_IMAGE_H */")

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\n  Written: {output_path} ({os.path.getsize(output_path)} bytes)")
    print(f"  Copy this file to esp32_inference/ to replace input_image.h")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: python {sys.argv[0]} <image_path> [output_path]")
        print(f"  Default output: ../esp32_inference/input_image.h")
        sys.exit(1)

    image_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "esp32_inference", "include", "input_image.h")

    if not os.path.exists(image_path):
        print(f"Error: {image_path} not found")
        sys.exit(1)

    convert_image(image_path, output_path)

    try:
        import onnxruntime as ort

        # Load same image and run inference
        img = Image.open(image_path).convert("RGB")
        img = img.resize((32, 32), Image.BILINEAR)
        arr = np.array(img, dtype=np.float32) / 255.0
        for c in range(3):
            arr[:, :, c] = (arr[:, :, c] - CIFAR10_MEAN[c]) / CIFAR10_STD[c]
        inp = arr.transpose(2, 0, 1).reshape(1, 3, 32, 32)

        print("\n  --- ONNX Runtime Reference ---")
        for model_name in [os.path.join(os.path.dirname(__file__), "..", "models", "model_int8.onnx")]:
            sess = ort.InferenceSession(model_name)
            result = sess.run(None, {"input": inp})[0]
            exp_x = np.exp(result[0] - np.max(result[0]))
            probs = exp_x / exp_x.sum()
            pred = np.argmax(probs)
            print(f"  Model: {model_name}")
            print(f"  Predicted: {pred} ({CIFAR10_CLASSES[pred]}) = {probs[pred]*100:.2f}%")
            top3 = np.argsort(probs)[::-1][:3]
            for rank, idx in enumerate(top3):
                print(f"    #{rank+1}: [{idx}] {CIFAR10_CLASSES[idx]} = {probs[idx]*100:.2f}%")
    except ImportError:
        print("\n  (onnxruntime not available, skipping reference inference)")

    print("=" * 50)


if __name__ == "__main__":
    main()
